### ISSUE TITLE
Possible shortcoming in DashboardExport::getRequiredAnalysisIds() or in the Sample code

### ISSUE THREAD

**Issue by pasirikala** [darwin-eu/DashboardExport#1]
When I run the Sample code, Achilles::achilles does not generate results for analysis 112.
After that, the DashboardExport::dashboardExport complains:
   Missing Achilles analysis ids in result tables: 112.

This seems to be caused by the following parameter not containing id 112.
`analysisIds = DashboardExport::getRequiredAnalysisIds()`

If I add 112 to the list returned by getRequiredAnalysisIds(), dashboardExport() works.

**Comment by MaximMoinat** [comment]
Thanks for reporting, we will fix this on the development branch.
